# Configuration file version
apiVersion: 1

# List of data sources to insert/update depending on what's available in the database.
datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
  access: proxy
  editable: true