services:
  prometheus:
    image: prom/prometheus 
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus_data:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - '9091:9091'
    networks:
      - monitoring

  alertmanager:
    image:  prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./alertmanager:/config
      - ./alertmanager_data:/alertmanager/data
    command:
      - '--config.file=/config/alertmanager.yml'
    ports:
      - '9093:9093'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana_data:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - monitoring

  consul:
    image: hashicorp/consul
    container_name: consul
    restart: unless-stopped
    volumes:
     - ./consul/server.json:/consul/config/server.json
     - ./consul_data:/consul/data
    ports:
      - '8500:8500'
      - '8600:8600/udp'
      - '8600:8600/tcp'
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
