---
## prometheus
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
  namespace: monitoring
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - alertmanager:9093
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: 'pushgateway'
        honor_timestamps: true
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - pushgateway:9091

---
## alertmanager
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-conf
  labels:
    name: alertmanager-conf
  namespace: monitoring
data:
  alertmanager.yaml: |-
    route:
      receiver: 'mail'
      repeat_interval: 4h
      group_by: [ alertname ]
    receivers:
      - name: 'mail'
        email_configs:
          - smarthost: 'smtp.gmail.com:465'
            auth_username: 'your_mail@gmail.com'
            auth_password: ""
            from: 'your_mail@gmail.com'
            to: 'some_mail@gmail.com'

---
## grafana
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf
  labels:
    name: grafana-conf
  namespace: monitoring
data:
  grafana.ini: |-
    [server]
    domain = monitoring.unity.com
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true

---
## grafana-datasource
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    name: grafana-datasource
  namespace: monitoring
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      orgId: 1
      url: http://prometheus:9090
      isDefault: true
      access: proxy
      editable: true
      basicAuth: false
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      editable: false

---
## loki
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-conf
  labels:
    name: loki-conf
  namespace: monitoring
data:
  loki.yaml: |-
    auth_enabled: false
    server:
      http_listen_port: 3100
      # grpc_listen_port: 9096
    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100
    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h
    ruler:
      alertmanager_url: http://alertmanager:9093