---
## prometheus
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  # storageClassName: monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
## alertmanager
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
  namespace: monitoring
spec:
  # storageClassName: monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
## grafana
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  # storageClassName: monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
## loki
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  # storageClassName: monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
## consul
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
  namespace: monitoring
spec:
  # storageClassName: monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi